package io.github.matheusproencaz.calcme.desafio.service.exception;

public class NotFoundUsersException extends RuntimeException{
    public NotFoundUsersException() {
    }
}
